# <?= ucfirst($this->sectionName) ?>


<?php foreach ($this->sectionData as $project) { ?>

## <?= $project['name'] ?> (<?= $this->dateRange($project['startDate'], $project['endDate']) ?>)
    <?php if (!empty($project['url'])) { ?>

=> <?= $project['url'] ?> <?= $project['entity'] ?>
    <?php } else { ?>

<?= $project['entity'] ?>
    <?php } ?>


<?= !empty($project['description']) ? ltrim($project['description'], '#') : '' ?>

    <?php if (!empty($project['highlights'])) { ?>
        <?php foreach ($project['highlights'] as $highlight) { ?>

* <?= $highlight ?>
        <?php } ?>
    <?php } ?>

<?php } ?>